### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by iamMoid** [UBC-MDS/magmavizR#15]

**Comment by iamMoid** [comment]
Changes we need to make to the README:
1. Update function descriptions to be in sync with magmaviz package
2. Update Usage section

**Comment by ruben1dlg** [comment]
The description for Corrplot is already updated with the functionalities it will have in this package. For the usage I think this is what we should add something like this:

``` 
install.packages("UBC-MDS/magmavizR")
corrplot(df, print_corr = TRUE, title = "Correlation Plot")
```

**Comment by iamMoid** [comment]
Yes that makes sense. We can follow the same documentation style as the Python counterpart.

**Comment by iamMoid** [comment]
> The description for Corrplot is already updated with the functionalities it will have in this package. For the usage I think this is what we should add something like this:
> 
> ```
> install.packages("UBC-MDS/magmavizR")
> corrplot(df, print_corr = TRUE, title = "Correlation Plot")
> ```

"While the default plot would use circle shapes, an auxiliary input provides the flexibility to switch to square shapes." This sentence holds true for the R package as well right? If yes, I will update the description for corrplot function.

**Comment by miyer26** [comment]
There are no changes needed for the boxplot function Moid. Thanks for taking this up.

**Comment by iamMoid** [comment]
Also @ruben1dlg instead of `install.packages("UBC-MDS/magmavizR")`, I think it should be `library("magmavizR")` since the INSTALLATION section will cover how to install the package?

**Comment by iamMoid** [comment]
@miyer26 I like @ruben1dlg idea of loading the library and showing a sample function call. Will add for all functions.

**Comment by ruben1dlg** [comment]
> > The description for Corrplot is already updated with the functionalities it will have in this package. For the usage I think this is what we should add something like this:
> > ```
> > install.packages("UBC-MDS/magmavizR")
> > corrplot(df, print_corr = TRUE, title = "Correlation Plot")
> > ```
> 
> "While the default plot would use circle shapes, an auxiliary input provides the flexibility to switch to square shapes." This sentence holds true for the R package as well right? If yes, I will update the description for corrplot function.

@iamMoid That 'shape' input is not used in the R version of the function. For now we can keep the description as it is already in the README.

**Comment by miyer26** [comment]
@ruben1dlg @iamMoid I agree that this will be the best approach.

**Comment by shyan0903** [comment]
@iamMoid Thank you for creating this issue! For the description for histogram(), could you please update "a categorical feature" to "a numeric feature" since in R, geom_bar is used for categorical features?
 My usage is:
`histogram(mtcars, wt, "..count..")`

Thank you!

**Comment by iamMoid** [comment]
PR ready for your review!
